### ISSUE TITLE
Tracking issues of Data Lake with Iceberg Support

### ISSUE THREAD

**Issue by Xuanwo** [databendlabs/databend#12272]
After the close of https://github.com/datafuselabs/databend/issues/11947, Databend has completed all preparation work required for implementing data lake support!

**Databend now has multi-catalog support!**

We can create a new catalog like:

```sql
CREATE CATALOG iceberg_ctl
TYPE=ICEBERG
CONNECTION=(
    URL='s3://testbucket/iceberg_ctl/'
    AWS_KEY_ID='minioadmin'
    AWS_SECRET_KEY='minioadmin'
    ENDPOINT_URL='${STORAGE_S3_ENDPOINT_URL}'
);
```

And we can show/drop them:

```sql
SHOW DATABASES IN iceberg_ctl;
SHOW TABLES IN iceberg_ctl.iceberg_db;
DROP CATALOG IF EXISTS iceberg_ctl
```

**Databend now can read existing iceberg!**

We can query data in an exisint iceberg table like the following:

```sql
SELECT count(*) FROM iceberg_ctl.iceberg_db.iceberg_tbl;
```

We have found a way to add data features in Databend. I have some ideas that we can start working on:

## Tasks

Our current goal is to make reading from iceberg table fast and reliable.

- [x] Implement push_down for iceberg table
- [x] Implement iceberg rest catalog support
- [x] Work with iceberg community to build [iceberg-rust](https://github.com/apache/iceberg-rust/)

**Comment by chrisfw** [comment]
Hi @Xuanwo , this is an exciting feature!  I was wondering though, if the initial implementation supports iceberg's temporal/as-of queries?

Regards,
Chris Whelan

**Comment by atifiu** [comment]
Currently, databend support querying Iceberg tables with partition on timestamp column with day/month/year transformation or does task "Implement partiation for iceberg table" means the same ?

**Comment by BohuTANG** [comment]
@Xuanwo This issue need update?

**Comment by Xuanwo** [comment]
> [@Xuanwo](https://github.com/Xuanwo) This issue need update?

I believe we can close this now and track the detailed work in separate issues.

**Comment by sundy-li** [comment]
see https://docs.databend.com/guides/access-data-lake/iceberg for databend work with iceberg
