### ISSUE TITLE
Tracking: Geometry types

### ISSUE THREAD

**Issue by ariesdevil** [databendlabs/databend#14543]
**Summary**

- [x] initial support geometry type. #14470 
- [x] support create table with geometry type. #14615 
- [ ] add more functions to geometry type
- [ ] add helpers for serde and show geometry types
- [ ] after all, write many tests for this features
- [ ] add docs
- [x] support geography type [#16286]

**Comment by kkk25641463** [comment]
I found that ST_GEOMFROMGEOHASH() returned value is geojson type ([doc](https://docs.snowflake.com/en/sql-reference/functions/st_geomfromgeohash) ). Should we implement subtypes with geometry type like number type or decimal type? And [output](https://github.com/datafuselabs/databend/blob/f5478ff8f0e00acc1cb340e31301a77b2dedf9b7/src/query/expression/src/utils/display.rs#L256) can be choose with subtypes like ewkb、ewkt、geojson.
