### ISSUE TITLE
Tracking issue: RBAC improvement plan in 2024 Q1

### ISSUE THREAD

**Issue by TCeason** [databendlabs/databend#14618]
We have now completed the first phase of RBAC. After these pr merged(#14567, #14514, #14501, #14393, #14380, #14344, #14333) both permissions and RBAC ensure Forward/Backward compatibility.

So we can start the second phase of work

1. Cover more object in RBAC and refined permission check to to split super privilege.
2. semantic alignment with sf

**Summary**

### Important 

- [x] add some doc about rbac, ownership

- [x] #14572 
- [x] #14464
- [x] #14699
- [x] #14788
- [x] #14918
- [x] https://github.com/datafuselabs/databend/issues/15052
- [x] #14616
- [ ] #13323

### The following tasks can be performed upon request

- [ ] https://github.com/datafuselabs/databend/issues/14463
- [ ] feat: cover privilege check about connection
- [ ] feat: cover privilege check about warehouse

- [ ] #13505
- [ ] feat: cover privilege  & owner check about Stream 

- [ ] feat: cover privilege  & owner check about Share/ShareEndpoint

- [ ] feat: cover privilege  & owner check about DataMask

- [ ] Refactor: only admin user can CRUD index

- [ ] Refactor: only admin user can CRUD FileFormat

- [x] #14463

- [ ] Refactor: More refined permission management (RenameDatabase/AlterUDF/RevertTable/CRUD_Virtual_Column)

- [ ] feat: NetworkPolicy, PasswordPolicy need add ownership(low )
