### ISSUE TITLE
Tracking: StringView data type

### ISSUE THREAD

**Issue by ariesdevil** [databendlabs/databend#14813]
**Summary**

- [x] impls string view for databend arrow #14662 
- [x] impls kernel compute for this type
- [x] impls string view for apache arrow-rs(progress: https://github.com/apache/arrow-rs/issues/5374)
- [x] replace current string column to new string view type #16610 
- [x] optimize filter/take/concat performance of string view  #16610 
- [x] #16775

**Comment by sundy-li** [comment]
Arrow-rs is ready for string view type.

Let's continue the task!

**Comment by sundy-li** [comment]
done in #16610
