### ISSUE TITLE
Refactor: upgrade QuotaMgr to using protobuf 

### ISSUE THREAD

**Issue by drmingdrmer** [databendlabs/databend#15009]
#### The problem

Currently QuotaMgr write json data into meta-service:
https://github.com/drmingdrmer/databend/blob/f248f211c9418e153d74515d0a755fbda11ef3ec/src/query/management/src/quota/quota_mgr.rs#L73

Json does not provide compatibility support as `FromToProto` does:
https://github.com/drmingdrmer/databend/blob/6332061fb2c8466c398b417cc6db878ba5933740/src/meta/proto-conv/src/from_to_protobuf.rs#L18

The setting data read/write should be upgrade to using `FromToProto` to provide well defined and tested backward compatibility.

#### TODO

- [x] keep the writing part unchanged, but read in pb/json compatible way.
- [ ] upgrade to write pb data instead of json.
- [ ] upgrade to read only pb format.
