### ISSUE TITLE
Feature: Integrate Databend PushDown with Iceberg Rust's Scan Planning

### ISSUE THREAD

**Issue by Xuanwo** [databendlabs/databend#16415]
**Summary**

Iceberg Rust has implemented scan planning, let's integrate with it directly instead.

## Tasks

- [x] https://github.com/apache/iceberg-rust/pull/609
- [ ] Integrate PushDown with iceberg-rust task scan
  - [ ] Implement projection
  - [ ] Implement expr transform
