### ISSUE TITLE
[WIP][RFC] databend playground

### ISSUE THREAD

**Issue by flaneur2020** [databendlabs/databend#2303]
Databend is a distributed system with multiple components, a typical production cluster includes at least 3 metasrv nodes, at least 1 querysrv node, and the storage layer (s3). To make experiencing a "real" databend cluster easier, we'd hope make a playground tool, allowing us provisioning a new testing cluster to explore the usability of Databend.

## Goal

- Allowing user start a playground daemon in the local machine, which exposes an interactive web UI
- (Maybe in the next iteration) Build a wasm packaged databend, allowing users access the interactive web UI in their browsers

## Todos

- [ ] make a simple web UI
- [ ] make a standalone playground server binary allowing bendctl to manage it
- [ ] a querying HTTP API

## References

- https://docs.pingcap.com/tidb/stable/tiup-playground

**Comment by ZhiHanZ** [comment]
> maybe we could take `playground` as a predefined profile?
> 
> Not sure if I am understanding this right:
> 
> * bendctl can have multiple databend installations in my local machine, like `test1”`, `test2`, these installations has isolated data directory and diferent ports
> * we could access diferent databend installations via different config "profile" or "context" like `~/.databend/profiles/test1.json`, and switch profiles like `kubectl config use-context` to access one cluster
> * so what does `bendctl up --playground` do could just be installing the components with a predefined config, with a generated profile config named `playground` allowing users easily access this installation.

currently profile is designed to support local(run on bare metal machine) and cluster (configure through kubernetes operator)
playground semantics could be a default configure with the following steps:
1. `bendctl cluster create --profile local` which bootstrap all cluster instances from local
2. `bendctl dashboard <observability plugins>` which would install observability plugins on local machine( similar to istio dashboard)
3. install frontend web UI and show UI on browser

so I think current profile definition is fine, and we just need to add plugins to existing local profiles

**Comment by ZhiHanZ** [comment]
Plus I think statically linked musl build binaries(similar to CGO_ENABLED=0 go build) has higher priority comparing to WASM plugins, since it will minimize the `libc` related dependencies run on production
