### ISSUE TITLE
Refactor internal table cache to use opendal

### ISSUE THREAD

**Issue by Xuanwo** [databendlabs/databend#8167]
We have the following cache now:

```rust
pub type SegmentInfoCache = ItemCache<SegmentInfo>;
pub type TableSnapshotCache = ItemCache<TableSnapshot>;
/// Cache bloom filter.
/// For each index block, columns are cached individually.
pub type BloomIndexCache = BytesCache;
/// FileMetaCache of bloom filter index data.
/// Each cache item per block
pub type BloomIndexMetaCache = ItemCache<FileMetaData>;

pub type FileMetaDataCache = ItemCache<FileMetaData>;
```

We will unify them into the one cache operator so users can configure them to

- memory (maybe moka based)
- local fs
- redis / Memcached

## Tasks

- [x] https://github.com/datafuselabs/databend/pull/8166
- [x] https://github.com/datafuselabs/opendal/issues/844
- [x] https://github.com/datafuselabs/opendal/issues/845
- [x] Add cache operator in databend
- [ ] Refactor memory-cache related logic
