### ISSUE TITLE
Tracking issue for Iceberg Table support

### ISSUE THREAD

**Issue by ClSlaid** [databendlabs/databend#8216]
**Summary**

- [x] Support multiple catalog in databend #8436 
- [x] #8874
- [ ] Support simple query on Iceberg
- [ ] [planned] Support schema evolution on Iceberg

**Comment by Xuanwo** [comment]
Iceberg has a lot of features. At the first stage of adding iceberg table support, I think we should keep focused. Start from the simplest query and thinks about what we should do instead of picking features from iceberg feature sets.

For example: `select * from my_iceberg_table`. What we should do to support this? Other features that not related to this should be marked as `planned` (like schema evolution).

**Comment by ClSlaid** [comment]
I think it's time to work on this.

**Comment by sundy-li** [comment]
let's move into #12272
