### ISSUE TITLE
Tracking: support `select ... from @<stage>`

### ISSUE THREAD

**Issue by youngsofun** [databendlabs/databend#9847]
**Summary**

__Features__

- [x] basic select from parquet
- [x] `select ... from @<stage> ( <select_stage_options> )` <alias>
     - [x]  https://github.com/datafuselabs/databend/pull/9877
- [x] distributed query
  - [x] list file in read_partitions https://github.com/datafuselabs/databend/pull/9871
- [x]  https://github.com/datafuselabs/databend/issues/9908
- [x] https://github.com/datafuselabs/databend/issues/9974
- [x] doc https://github.com/datafuselabs/databend/pull/10208
- [x] options
     - [x]  file_format

__Bugs__
- [ ] https://github.com/datafuselabs/databend/issues/9884

__Related__

- [x] [create format clause](https://github.com/datafuselabs/databend/issues/8100), so we can use  format name in `<select_stage_options>`

__Optional__

- [ ] error tolerant (not necessary if not used in copy) 
- [ ] select from json(low priority)
- [ ] select from CSV / TSV(low priority)

**Comment by youngsofun** [comment]
@BohuTANG @sundy-li 
do we need a `desc @stage/path` or  `infer_schema @stage/path`  like `desc table` ?
not know which columns can be used.

**Comment by youngsofun** [comment]
is `select ... from '<uri>'`  necessary?
need to design a syntax to pass `connection = (...) `

**Comment by BohuTANG** [comment]
> @BohuTANG @sundy-li @Xuanwo do we need a `desc @stage/path` or `infer_schema @stage/path` like `desc table` ? not know which columns can be used.

Better to have it, we can use it as:
1. For the cloud, we can infer the parquet schema
2. For debugging the schema

**Comment by BohuTANG** [comment]
> is `select ... from '<uri>'` necessary? need to design a syntax to pass `connection = (...) `

Good idea, it is still better to have, but this task can be considered as low priority.

**Comment by BohuTANG** [comment]
@youngsofun Add `desc @stage/path` to this tracking, really need it.

**Comment by youngsofun** [comment]
since select from stage looks like a table function ( with @stage_name as function name) .
should we put the doc under [table-functions](https://databend.rs/doc/reference/functions/table-functions) too?

**Comment by BohuTANG** [comment]
> since select from stage looks like a table function ( with `@stage_name` as function name) . should we put the doc under [table-functions](https://databend.rs/doc/reference/functions/table-functions) too?

Ok
